instance = "example"
gpg-key = "example"
archive-directory = ".chillbox"

[[user]]
name = "bob"

[env]
ENVIRONMENT = "development"

[[secret]]
id = "access_key_id"
name = "ACCESS_KEY_ID"
prompt = "Enter the access key id for the S3 object storage being used."
expires = 2023-08-16
owner = "bob"
[[secret.remote]]
append-dest = "/home/bob/env-secrets"
user = "bob"

[[secret]]
id = "secret_access_key"
name = "SECRET_ACCESS_KEY"
prompt = "Enter the secret access key for the S3 object storage being used."
expires = 2023-08-16
owner = "bob"
[[secret.remote]]
append-dest = "/home/bob/env-secrets"
user = "bob"


[[template]]
src = "chillbox-server/templates"
prefix = "chillbox-server"


[[path]]
id = "chillbox-s3-credentials"
src = "chillbox-server:s3-credentials.jinja"
dest = "/home/bob/.aws/credentials"
render = true
sensitive = true
# TODO Should be set with only read/write for user if sensitive
# chmod 0600 /home/bob/.aws/credentials
# chown bob:bob /home/bob/.aws/credentials


[[path]]
id = "chillbox-nginx-templates"
src = "chillbox-server/nginx/templates"
dest = "/etc/chillbox/nginx/templates"

[[path]]
id = "chillbox-bin"
src = "chillbox-server/bin"
dest = "/etc/chillbox/bin"

[[path]]
id = "chillbox-dep"
src = "chillbox-server/dep"
dest = "/var/lib/chillbox/python"

[[path]]
id = "chillbox-redis"
src = "chillbox-server/redis"
dest = "/etc/chillbox/redis"

[[path]]
id = "chillbox-nginx-conf"
src = "chillbox-server/nginx/nginx.conf"
dest = "/etc/nginx/nginx.conf"

[[path]]
id = "chillbox-nginx-default-conf"
src = "chillbox-server/nginx/default.nginx.conf"
dest = "/etc/nginx/conf.d/default.nginx.conf"

[[path]]
id = "chillbox-nginx-ssl_cert_include"
src = "chillbox-server/nginx/chillbox.ssl_cert.include"
dest = "/etc/nginx/conf.d/chillbox.ssl_cert.include"



[[server]]
ip = "127.0.0.1"
ssh_port = 10022
name = "local"
owner = "bob"
login-users = [ "alice:dev", "bob:dev" ]
secrets = [ "access_key_id", "secret_access_key" ]
remote-files = [
  "chillbox-s3-credentials",
  "chillbox-nginx-templates",
  "chillbox-bin",
  "chillbox-dep",
  "chillbox-redis",
  "chillbox-nginx-conf",
  "chillbox-nginx-default-conf",
  "chillbox-nginx-ssl_cert_include",
  ]
[server.user-data]
template = "chillbox:user-data.sh.jinja"
[server.user-data.context]
something = "example"
