---
- name: Update installed packages
  hosts: chillbox
  vars_files:
    - /run/tmp/ansible/terraform/vars.json
  tasks:
    - name: Update all installed packages to the latest versions
      become: true
      community.general.apk:
        upgrade: true
